/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.ChessPiece;
import Model.Position;
import java.awt.Color;

/**
 *
 * @author Callum
 */
public class GridSquare extends javax.swing.JPanel {

    private ChessPiece currentPiece = null;

    /**
     * Creates new form GridSquare
     */
    public GridSquare(Position position) {
        initComponents();
        int x = position.getX();
        int y = position.getY();

        /**
         * Colors the square based on the x and y coordinates
         */
        if (y % 2 == 0) {
            if (x % 2 == 0) {
                this.setBackground(Color.WHITE);
            } else {
                this.setBackground(Color.BLACK);
            }
        } else {
            if (x % 2 == 1) {
                this.setBackground(Color.WHITE);
            } else {
                this.setBackground(Color.BLACK);
            }
        }
    }

    /**
     * Sets the currentPiece for the square to be piece
     *
     * @param piece the piece to added to the square
     */
    public void addPiece(ChessPiece piece) {
        if (this.currentPiece == null) {
            currentPiece = piece;
        } else {

        }
    }

    /**
     * Removes the currentPiece from the square and replaces it with piece
     *
     * @param piece the piece to replace currentPiece
     */
    public void removePiece(ChessPiece piece) {

    }
    
    public void refresh() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
